name: Update Calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight UTC

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install lxml requests

    - name: Run script to update calendar
      run: python3 data/fetch_calendar.py

    - name: Show changes
      run: git diff

    - name: Check for changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/calendar.json
          git commit -m "update calendar.json"
          git push
        else
          echo "No changes detected"
        fi
